import { Language } from '../types';

export const translations = {
  ar: {
    appName: 'Discord Tools',
    tagline: 'كل ما تحتاجه لسيرفر ديسكورد الخاص بك',
    navHome: 'الرئيسية',
    navFiles: 'مركز الملفات',
    navTools: 'الأدوات',
    navBots: 'البوتات',
    navSettings: 'الإعدادات',

    // Home
    welcomeTitle: 'أدوات ديسكورد المتكاملة',
    welcomeSubtitle: 'منصة خفيفة وسريعة توفر كل الأدوات الأساسية لمجتمع ديسكورد',
    fileCenterCardTitle: '📁 مركز الملفات',
    fileCenterCardDesc: 'رفع ومشاركة الملفات حتى 50MB بدون تسجيل دخول مع روابط مباشرة',
    toolsCardTitle: '🛠️ أدوات ديسكورد',
    toolsCardDesc: 'طوابع زمنية، صانع الـ Embeds، حاسبة الصلاحيات، الويب هوك، والألوان',
    botsCardTitle: '🤖 دليل البوتات',
    botsCardDesc: 'أفضل بوتات الديسكورد الموثوقة مع روابط الدعوة المباشرة والتفاصيل',
    popularToolsTitle: 'الأدوات الأكثر استخداماً',
    openSection: 'فتح القسم',

    // File Center
    fileCenterTitle: 'مركز رفع ومشاركة الملفات',
    fileCenterSubtitle: 'ارفع أي نوع من الملفات حتى 50 ميغابايت واحصل على رابط مشاركة فوري',
    uploadZonePrompt: 'انقر لاختيار ملف من هاتفك أو اسحبه هنا',
    maxSizeNote: 'الحد الأقصى لحجم الملف: 50 MB (جميع الامتدادات مقبولة)',
    selectedFile: 'الملف المختار',
    fileName: 'اسم الملف:',
    fileSize: 'الحجم:',
    fileType: 'النوع:',
    uploadBtn: 'بدء الرفع الآن',
    uploadingStatus: 'جاري رفع الملف إلى السحابة...',
    uploadSuccess: 'تم رفع الملف بنجاح!',
    uploadError: 'فشل في رفع الملف',
    errFileTooBig: 'عذراً! حجم الملف يتجاوز الحد الأقصى المسموح به (50 ميغابايت). يرجى اختيار ملف أصغر.',
    shareLinkTitle: 'رابط المشاركة المباشر',
    copyLink: 'نسخ الرابط',
    shareLink: 'مشاركة الرابط',
    downloadFile: 'تحميل الملف',
    openInBrowser: 'فتح الرابط',
    discordMarkdownCode: 'كود المشاركة في ديسكورد',
    copiedSuccess: 'تم النسخ إلى الحافظة بنجاح!',
    recentUploads: 'الملفات المرفوعة حديثاً',
    noRecentUploads: 'لم تقم برفع أي ملفات حتى الآن.',
    uploadAnother: 'رفع ملف آخر',
    directUrl: 'الرابط المباشر:',

    // Bots Directory
    botsTitle: 'دليل بوتات Discord',
    botsSubtitle: 'استكشف أفضل البوتات لإدارة وتطوير سيرفرك بكل سهولة',
    searchBotsPlaceholder: 'ابحث عن اسم البوت أو الوظيفة...',
    categoryAll: 'الكل',
    catModeration: 'إشراف',
    catMusic: 'موسيقى',
    catSecurity: 'حماية وأمان',
    catUtility: 'خدمات وأدوات',
    catFun: 'ترفيه وميمز',
    catEconomy: 'اقتصاد وعملات',
    inviteBot: 'دعوة البوت',
    botDetails: 'التفاصيل',
    closeDetails: 'إغلاق',
    prefix: 'البادئة (Prefix):',
    developer: 'المطور:',
    features: 'الميزات الرئيسية:',
    noBotsFound: 'لم يتم العثور على أي بوت يطابق بحثك.',

    // Tools
    toolsHeaderTitle: 'أدوات ديسكورد المفيدة',
    toolsHeaderSubtitle: 'تعمل جميع الأدوات محلياً وبشكل فوري بدون الحاجة لاتصال خارجي',
    toolTimestamp: 'مولد الطوابع الزمنية',
    toolEmbed: 'صانع الـ Embeds',
    toolPermissions: 'حاسبة الصلاحيات',
    toolWebhook: 'صانع رسائل الويب هوك',
    toolColor: 'مولد ألوان ديسكورد',

    // Timestamp Generator
    timestampDesc: 'أنشئ توقيتات ديسكورد ديناميكية تظهر لكل عضو حسب منطقته الزمنية تلقائياً',
    selectDate: 'اختر التاريخ:',
    selectTime: 'اختر الوقت:',
    nowBtn: 'الوقت الحالي',
    displayStyle: 'شكل العرض:',
    generatedCode: 'كود ديسكورد:',
    previewText: 'معاينة في ديسكورد:',
    copyTimestamp: 'نسخ كود التوقيت',

    // Embed Builder
    embedDesc: 'صمم رسائل Embed متطورة مع ألوان وحقول وعناوين وانسخ بيانات JSON',
    embedTitle: 'عنوان الرسالة',
    embedDescLabel: 'نص الرسالة (الوصف)',
    embedUrl: 'رابط العنوان (اختياري)',
    embedColor: 'لون الشريط الجانبي',
    authorSettings: 'بيانات الكاتب (Author)',
    authorName: 'اسم الكاتب',
    authorIcon: 'رابط صورة الكاتب',
    footerSettings: 'التذييل (Footer)',
    footerText: 'نص التذييل',
    footerIcon: 'رابط صورة التذييل',
    includeTimestamp: 'إرفاق التوقيت الحالي',
    imagesSection: 'الصور المرفقة',
    imageUrl: 'رابط الصورة الرئيسية الكبيرة',
    thumbnailUrl: 'رابط الصورة المصغرة (Thumbnail)',
    fieldsSection: 'الحقول المخصصة (Fields)',
    addField: '+ إضافة حقل جديد',
    fieldName: 'عنوان الحقل',
    fieldValue: 'قيمة الحقل',
    inlineToggle: 'في نفس السطر (Inline)',
    removeField: 'حذف الحقل',
    copyEmbedJson: 'نسخ كود JSON للـ Embed',
    embedLivePreview: 'معاينة مباشرة كما تظهر في ديسكورد',

    // Permissions Calculator
    permDesc: 'احسب قيمة بتات الصلاحيات (Bitwise Permissions) لإنشاء روابط دعوة البوتات',
    permAdmin: 'صلاحيات المدير (Administrator)',
    permTotalValue: 'قيمة الصلاحية المحسوبة (Permission Integer):',
    permSelectAll: 'تحديد الكل',
    permClearAll: 'إلغاء التحديد',
    permPresetAdmin: 'مدير كامل (Admin)',
    permPresetMod: 'مشرف (Moderator)',
    permPresetStandard: 'عضو عادي (Standard)',
    clientIdLabel: 'معرف تطبيق البوت (Client ID):',
    inviteUrlLabel: 'رابط دعوة البوت التلقائي:',
    copyPermValue: 'نسخ رقم الصلاحية',
    copyInviteUrl: 'نسخ رابط الدعوة',

    // Webhook Builder
    webhookDesc: 'صمم رسائل Webhook مخصصة مع اسم مستعار وصورة شخصية',
    webhookUrlLabel: 'رابط الويب هوك (Discord Webhook URL):',
    webhookUsername: 'اسم البوت / المرسل المستعار',
    webhookAvatar: 'رابط الصورة الشخصية (Avatar URL)',
    webhookContent: 'نص الرسالة',
    attachEmbedToggle: 'إرفاق الـ Embed المصمم أعلاه مع الرسالة',
    copyWebhookJson: 'نسخ حمولة JSON (Payload)',
    sendWebhookBtn: 'إرسال تجريبي إلى ديسكورد',
    webhookSentSuccess: 'تم إرسال الرسالة إلى سيرفر ديسكورد بنجاح!',
    webhookSendError: 'فشل في إرسال الرسالة. يرجى التأكد من صحة رابط الويب هوك.',

    // Color Generator
    colorDesc: 'اختر أي لون واحصل على قيم HEX و Decimal المطلوبة لكود ديسكورد',
    discordPresets: 'ألوان ديسكورد الرسمية:',
    hexLabel: 'رمز الـ HEX:',
    decimalLabel: 'القيمة العشرية (Discord Decimal):',
    rgbLabel: 'صيغة RGB:',
    hslLabel: 'صيغة HSL:',
    copyColor: 'نسخ',

    // Settings
    settingsTitle: 'إعدادات التطبيق',
    settingsSubtitle: 'تخصيص اللغة والمظهر ومعلومات النظام والمشروع',
    langSetting: 'لغة التطبيق',
    themeSetting: 'مظهر التطبيق',
    themeDark: 'الوضع الداكن (Dark Mode)',
    themeLight: 'الوضع الفاتح (Light Mode)',
    startIoSection: 'إعلانات Start.io',
    startIoAppId: 'معرف التطبيق (App ID): 208250285',
    startIoStatus: 'الحالة: نشط ومتوافق مع سياسات الأمان',
    supabaseSection: 'الاتصال بقاعدة بيانات Supabase',
    supabaseProjectUrl: 'عنوان المشروع (Project URL):',
    supabaseStorageBucket: 'مستودع التخزين: discord-files (عام ومحمي بـ RLS)',
    supabaseStatus: 'حالة الاتصال: جاهز للرفع المباشر بدون تسجيل دخول',
    aboutSection: 'حول تطبيق Discord Tools',
    aboutText: 'تطبيق خدمات وأدوات مساعدة مجاني لمجتمعات ديسكورد، يتيح رفع الملفات بسرعة وأمان وإدارة البوتات وحساب الصلاحيات وتوليد الأكواد دون تعقيد.',
    disclaimer: 'تنويه: هذا التطبيق هو أداة مساعدة مستقلة وليس تابعاً أو معتمداً من قِبل شركة Discord Inc بأي شكل.',
    privacySection: 'سياسة الخصوصية',
    privacyText: 'نحن نحترم خصوصيتك. الملفات المرفوعة تُخزن في مساحة Supabase المخصصة ولا نجمع أي بيانات شخصية أو معلومات تسجيل دخول.',
    appVersion: 'إصدار التطبيق',
    exportFlutterTitle: 'مشروع Flutter جاهز للبناء (APK)',
    exportFlutterDesc: 'تم تجهيز كود Flutter الكامل في المجلدات مع pubspec.yaml وملفات Dart و AndroidManifest.xml.',
  },
  en: {
    appName: 'Discord Tools',
    tagline: 'Everything you need for your Discord server',
    navHome: 'Home',
    navFiles: 'File Center',
    navTools: 'Tools',
    navBots: 'Bots',
    navSettings: 'Settings',

    // Home
    welcomeTitle: 'Discord Tools Hub',
    welcomeSubtitle: 'Lightweight, fast, and practical utilities built for Discord creators and users',
    fileCenterCardTitle: '📁 File Center',
    fileCenterCardDesc: 'Upload and share files up to 50MB without login with instant public links',
    toolsCardTitle: '🛠️ Discord Tools',
    toolsCardDesc: 'Timestamp generator, embed builder, permissions calculator, webhook, and colors',
    botsCardTitle: '🤖 Discord Bots',
    botsCardDesc: 'Curated list of essential Discord bots with direct invite links and details',
    popularToolsTitle: 'Popular Tools',
    openSection: 'Open Section',

    // File Center
    fileCenterTitle: 'File Center & Storage',
    fileCenterSubtitle: 'Upload any file up to 50MB and generate shareable links instantly',
    uploadZonePrompt: 'Click to select a file from your phone or drag it here',
    maxSizeNote: 'Maximum file size: 50 MB (All file types supported)',
    selectedFile: 'Selected File',
    fileName: 'File Name:',
    fileSize: 'Size:',
    fileType: 'Type:',
    uploadBtn: 'Start Upload',
    uploadingStatus: 'Uploading file to cloud storage...',
    uploadSuccess: 'File uploaded successfully!',
    uploadError: 'Failed to upload file',
    errFileTooBig: 'File exceeds the maximum limit of 50 MB. Please select a smaller file.',
    shareLinkTitle: 'Public Share Link',
    copyLink: 'Copy Link',
    shareLink: 'Share Link',
    downloadFile: 'Download File',
    openInBrowser: 'Open in Browser',
    discordMarkdownCode: 'Discord Markdown Link',
    copiedSuccess: 'Copied to clipboard!',
    recentUploads: 'Recent Uploads',
    noRecentUploads: 'No files uploaded yet.',
    uploadAnother: 'Upload Another File',
    directUrl: 'Direct URL:',

    // Bots Directory
    botsTitle: 'Discord Bots Directory',
    botsSubtitle: 'Explore top rated bots to level up and protect your Discord server',
    searchBotsPlaceholder: 'Search bots by name or functionality...',
    categoryAll: 'All',
    catModeration: 'Moderation',
    catMusic: 'Music',
    catSecurity: 'Security',
    catUtility: 'Utility',
    catFun: 'Fun',
    catEconomy: 'Economy',
    inviteBot: 'Invite Bot',
    botDetails: 'Details',
    closeDetails: 'Close',
    prefix: 'Prefix:',
    developer: 'Developer:',
    features: 'Key Features:',
    noBotsFound: 'No bots found matching your query.',

    // Tools
    toolsHeaderTitle: 'Discord Tools Collection',
    toolsHeaderSubtitle: 'All utilities run 100% locally and instantly without backend delay',
    toolTimestamp: 'Timestamp Generator',
    toolEmbed: 'Embed Builder',
    toolPermissions: 'Permissions Calculator',
    toolWebhook: 'Webhook Builder',
    toolColor: 'Color Generator',

    // Timestamp Generator
    timestampDesc: 'Create dynamic Discord timestamps that automatically adapt to each user\'s timezone',
    selectDate: 'Select Date:',
    selectTime: 'Select Time:',
    nowBtn: 'Current Time',
    displayStyle: 'Display Style:',
    generatedCode: 'Discord Code:',
    previewText: 'Discord Preview:',
    copyTimestamp: 'Copy Timestamp Code',

    // Embed Builder
    embedDesc: 'Create custom rich Discord embeds with fields, colors, images and copy the JSON',
    embedTitle: 'Embed Title',
    embedDescLabel: 'Message Description',
    embedUrl: 'Title URL (optional)',
    embedColor: 'Sidebar Color',
    authorSettings: 'Author Info',
    authorName: 'Author Name',
    authorIcon: 'Author Icon URL',
    footerSettings: 'Footer Info',
    footerText: 'Footer Text',
    footerIcon: 'Footer Icon URL',
    includeTimestamp: 'Include Current Timestamp',
    imagesSection: 'Images',
    imageUrl: 'Large Image URL',
    thumbnailUrl: 'Thumbnail URL',
    fieldsSection: 'Custom Fields',
    addField: '+ Add New Field',
    fieldName: 'Field Name',
    fieldValue: 'Field Value',
    inlineToggle: 'Inline',
    removeField: 'Remove Field',
    copyEmbedJson: 'Copy Embed JSON',
    embedLivePreview: 'Live Discord Preview',

    // Permissions Calculator
    permDesc: 'Compute bitwise permission flags to generate secure bot invite links',
    permAdmin: 'Administrator',
    permTotalValue: 'Calculated Permission Integer:',
    permSelectAll: 'Select All',
    permClearAll: 'Clear All',
    permPresetAdmin: 'Admin',
    permPresetMod: 'Moderator',
    permPresetStandard: 'Standard Member',
    clientIdLabel: 'Bot Application Client ID:',
    inviteUrlLabel: 'Generated Bot Invite URL:',
    copyPermValue: 'Copy Permission Integer',
    copyInviteUrl: 'Copy Invite URL',

    // Webhook Builder
    webhookDesc: 'Compose custom webhook messages with custom names, avatars, and embeds',
    webhookUrlLabel: 'Discord Webhook URL:',
    webhookUsername: 'Custom Username / Bot Name',
    webhookAvatar: 'Custom Avatar URL',
    webhookContent: 'Message Content',
    attachEmbedToggle: 'Attach Embed defined above',
    copyWebhookJson: 'Copy Webhook JSON Payload',
    sendWebhookBtn: 'Send Test to Discord',
    webhookSentSuccess: 'Message delivered to Discord webhook successfully!',
    webhookSendError: 'Failed to send message. Please check the Webhook URL.',

    // Color Generator
    colorDesc: 'Pick any color and get HEX, Discord Decimal, RGB, and HSL formats',
    discordPresets: 'Discord Color Presets:',
    hexLabel: 'HEX Code:',
    decimalLabel: 'Discord Decimal:',
    rgbLabel: 'RGB Format:',
    hslLabel: 'HSL Format:',
    copyColor: 'Copy',

    // Settings
    settingsTitle: 'App Settings',
    settingsSubtitle: 'Customize language, theme, and view project integration details',
    langSetting: 'Language',
    themeSetting: 'Theme Mode',
    themeDark: 'Dark Mode (Discord)',
    themeLight: 'Light Mode',
    startIoSection: 'Start.io Ads',
    startIoAppId: 'App ID: 208250285',
    startIoStatus: 'Status: Active and compliant with ad policies',
    supabaseSection: 'Supabase Database & Storage',
    supabaseProjectUrl: 'Project URL:',
    supabaseStorageBucket: 'Storage Bucket: discord-files (Public with RLS)',
    supabaseStatus: 'Connection: Ready for anonymous uploads',
    aboutSection: 'About Discord Tools',
    aboutText: 'A fast, lightweight utility companion for Discord server owners, moderators, and users. Upload files, generate timestamps, format embeds, and discover top bots.',
    disclaimer: 'Disclaimer: This application is an independent utility tool and is not affiliated with or endorsed by Discord Inc.',
    privacySection: 'Privacy Policy',
    privacyText: 'We respect your privacy. Uploaded files are hosted on your configured Supabase storage bucket without requiring personal accounts or private information.',
    appVersion: 'App Version',
    exportFlutterTitle: 'Flutter Project Ready (APK)',
    exportFlutterDesc: 'Complete Flutter + Dart code with pubspec.yaml, services, and AndroidManifest is bundled in this repository.',
  }
};
